name: Make Keystore (run once)

on:
  workflow_dispatch:

jobs:
  make_keystore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate keystore
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          keytool -genkey -v \
            -keystore key.jks \
            -keyalg RSA \
            -keysize 4096 \
            -validity 10000 \
            -alias key \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEYSTORE_PASSWORD" \
            -dname "CN=My Chat, OU=None, O=None, L=None, S=None, C=IR"
          base64 -w 0 key.jks > keystore-base64.txt

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: my-keystore
          path: |
            key.jks
            keystore-base64.txt
          retention-days: 1
